extern crate redict;
use redict::errors::BoxError;

fn main() -> Result<(), BoxError> {
    Ok(())
}
